"""Added enums into user table

Revision ID: a37ac459f946
Revises: cb94e2513ec3
Create Date: 2025-04-23 11:10:23.829494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37ac459f946'
down_revision: Union[str, None] = 'cb94e2513ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE roleenum AS ENUM ('DEMO', 'BASIK', 'PRO')")
    op.add_column('users', sa.Column('role', sa.Enum('DEMO', 'BASIC', 'PRO', name='roleenum'), server_default=sa.text("'DEMO'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE roleenum IF EXISTS")
    # ### end Alembic commands ###
